### ISSUE TITLE
[Query][sbi4onnx][Batch size]modification INPUT batch size will change OUTPUT batch size

### ISSUE THREAD

**Issue by joyoki** [PINTO0309/simple-onnx-processing-tools#5]
### Issue Type

Feature Request

### Model Name

Fast-BEV onnx model :[https://github.com/Sense-GVT/Fast-BEV](url)

### ONNX URL

https://github.com/Sense-GVT/Fast-BEV

### Description

Hi PINTO0309,
   Thanks for your work, first.
   I have two question to query
   1.I found if we change the **INPUT BATCH size** as 8, the **OUTPUT BATCH size** also will change to 8 
   the command as below
    `(base) joyoki@joyoki:~/fast-bev$ sbi4onnx -if fast-bev_orig.onnx -of fast-bev_orig_bat
ch8.onnx -ics 8
`
   i think this is not right, could you help double check, if we could change INPUT batch size and OUTPUT batch size Separated by need, such as 
    `sbi4onnx -if fast-bev_simply.onnx -ics 8 -of fast-bev_simply_batch6.onnx -ics 1`

2.I had checked some document, they both said:Modifying the batch size does not affect accuracy, only affects training speed and efficiency, is right?
orig model:https://drive.google.com/file/d/1gteHTEEJTwwMVYgJxO7zYrnHClL7lkTG/view?usp=share_link
![image](https://user-images.githubusercontent.com/4089228/225635972-359cbbc4-fd22-40b0-8429-6b9d920db60e.png)

Modified Model:https://drive.google.com/file/d/1x2Z_2psE-oQiqGuFK3OzXwrb0sitMMBE/view?usp=share_link
![image](https://user-images.githubusercontent.com/4089228/225635709-4416dcdd-aaf4-45ce-ba80-7bcd1e021bb1.png)

Thanks

### Relevant Log Output

INFO: Finish!,
no error

### URL or source code for simple inference testing code

Model link:https://drive.google.com/drive/folders/1NH0BFnBKD7xo6tbWHewSz8frZnxS_7cc?usp=sharing

**Comment by PINTO0309** [comment]
All Google Drive links are private.

**Comment by joyoki** [comment]
> All Google Drive links are private.

Sorry, please try this link,:https://drive.google.com/drive/folders/1NH0BFnBKD7xo6tbWHewSz8frZnxS_7cc?usp=sharing

i  will also will update the above link

Thanks

**Comment by PINTO0309** [comment]
Since the zero dimensionality is destroyed in the middle of the model, the zero dimensionality after this Reshape has no batch size significance.
![image](https://user-images.githubusercontent.com/33194443/225646764-d7156856-1f3c-4837-a5aa-4cb16b81afcb.png)
![image](https://user-images.githubusercontent.com/33194443/225648271-81804910-26e3-4c24-a81a-2a07b7d59fd0.png)
![image](https://user-images.githubusercontent.com/33194443/225646864-126e23d3-25d1-454e-b72d-fe1ac59bca47.png)

>2.I had checked some document, they both said:Modifying the batch size does not affect accuracy, only affects training speed and efficiency, is right?

Accuracy degradation would occur if the model had no concept of batch size, as this model does, or if the model actively destroys batch size. You should understand the structure of the model before asking questions. And I am not really interested in topics that have nothing to do with this repository.

**Comment by joyoki** [comment]
Hi PINTO0309,
   Sorry for my mistake about the batch size on the model fast-bev. I had read the document about fast-bev :https://arxiv.org/pdf/2301.07870.pdf
the INPUT should be 1x23x256x704, so the batch size should be 1.
    while I am still confuse, How to modify this omitted batch size like this example

Thanks
